require("perg.plugin_config.tokyonight")
require("perg.plugin_config.lualine")
require("perg.plugin_config.my_nvim-tree")
require("perg.plugin_config.telescope")
require("perg.plugin_config.treesitter")
require("perg.plugin_config.lsp_config")
